"""create incoming_sms table

Revision ID: 28816f09a30c
Revises: 
Create Date: 2025-12-03 14:23:31.491708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28816f09a30c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=64), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=False),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_sms_from_number'), 'incoming_sms', ['from_number'], unique=False)
    op.create_index(op.f('ix_incoming_sms_id'), 'incoming_sms', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_sms_provider_message_id'), 'incoming_sms', ['provider_message_id'], unique=True)
    op.create_index(op.f('ix_incoming_sms_received_at'), 'incoming_sms', ['received_at'], unique=False)
    op.create_index(op.f('ix_incoming_sms_status'), 'incoming_sms', ['status'], unique=False)
    op.create_index(op.f('ix_incoming_sms_to_number'), 'incoming_sms', ['to_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_sms_to_number'), table_name='incoming_sms')
    op.drop_index(op.f('ix_incoming_sms_status'), table_name='incoming_sms')
    op.drop_index(op.f('ix_incoming_sms_received_at'), table_name='incoming_sms')
    op.drop_index(op.f('ix_incoming_sms_provider_message_id'), table_name='incoming_sms')
    op.drop_index(op.f('ix_incoming_sms_id'), table_name='incoming_sms')
    op.drop_index(op.f('ix_incoming_sms_from_number'), table_name='incoming_sms')
    op.drop_table('incoming_sms')
    # ### end Alembic commands ###
